pipeline {
    agent {
       label "deploy"
    }
    stages {
          stage("connect") {
             steps {
               script {
                   sh '''
                   make image FILE=server.py VERSION=0.0.2
                   make push VERSION=0.0.2
                   make pull VERSION=0.0.2
                   '''
               }
             }
          }
        }
}