pipeline {
    agent {
       label "deploy"
    }
    stages {
          stage("connect") {
             steps {
               script {
                   sh '''
                   make image VERSION=show 
                   make image pull VERSION=show
                   '''
                   
               }
             }
          }
        }
}
