pipeline {
    agent {
       label "deploy"
    }
    stages {
          stage("connect") {
             steps {
               script {
                   sh '''
                   make image VERSION=cam_data FILE=./Modules/cam_data/Dockerfile BRANCH=null
                   make push VERSION=cam_data
                   make pull VERSION=cam_data
                   '''
               }
             }
          }
        }
}
