pipeline {
    agent {
       label "deploy"
    }
    stages {
          stage("connect") {
             steps {
               script {
                   sh '''
                   make image VERSION=reid BRANCH=null FILE=./Modules/reid/Dockerfile
                   make push VERSION=reid
                   make pull VERSION=reid  
                   '''
                   
               }
             }
          }
        }
}
