pipeline {
    agent {
       label "deploy"
    }
    stages {
          stage("connect") {
             steps {
               script {
                   sh '''
                   make image VERSION=detection BRANCH=null FILE=./Modules/detection/Dockerfile
                   make push VERSION=detection
                   make pull VERSION=detection  
                   '''
                   
               }
             }
          }
        }
}
